
# Bangla News Cross-Source Comparison
## Simple Zero-Shot Evaluation with Gemini, Qwen and Gemma

### Goal
For the **same incident**, compare how **different Bangla news portals** portray the news.

Pipeline:

**Dataset → Incident Grouping → Cross-Source Pairs → Gemini Reference → Qwen Zero-Shot → Gemma Zero-Shot → BLEU + BERTScore + ROUGE → Average Scores**

### Models
- **Reference:** `gemini-3.6-flash`
- **Qwen:** `Qwen/Qwen3-1.7B`
- **Gemma:** `google/gemma-3-4b-it`

### Final result
For every selected news pair, calculate:
- BLEU
- BERTScore Precision / Recall / F1
- ROUGE-1 F1
- ROUGE-2 F1
- ROUGE-L F1

Then calculate the **average of each metric across all evaluated pairs**.

> Nothing is saved to CSV. Everything is displayed directly in Colab.


# 1. Install packages

Use a fresh Google Colab runtime with **T4 GPU or stronger**.

Do not manually install or upgrade NumPy/Pandas.

In [5]:
%pip install -q \
    --upgrade-strategy only-if-needed \
    "transformers>=4.53.0" \
    datasets accelerate bitsandbytes \
    sacrebleu bert-score \
    google-genai huggingface_hub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 20.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 2.2 MB/s eta 0:00:00

# 2. Imports

In [6]:
import re
import gc
import random
import getpass
import string
import unicodedata
from itertools import combinations
from collections import Counter

import numpy as np
import pandas as pd
import torch

from datasets import load_dataset
from tqdm.auto import tqdm
from IPython.display import display

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError("Enable GPU in Colab: Runtime → Change runtime type → GPU")

GPU available: True
GPU: Tesla T4

# 3. Load the dataset

In [7]:
DATASET_NAME = "Bilash911/BanglaNewsDataset"

dataset = load_dataset(DATASET_NAME, split="train")
df = dataset.to_pandas()

df = df.dropna(subset=["Incident", "news body", "news source"]).copy()

for col in ["Incident", "news headline", "news body", "news source", "news link"]:
    df[col] = (
        df[col]
        .fillna("")
        .astype(str)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

df = df[
    (df["Incident"] != "")
    & (df["news body"] != "")
    & (df["news source"] != "")
].copy()

df = df.drop_duplicates(
    subset=["Incident", "news source", "news headline", "news body"]
).reset_index(drop=True)

print("Total usable articles:", len(df))
print("Unique incidents:", df["Incident"].nunique())
print("Unique news sources:", df["news source"].nunique())

display(df[["Incident", "news source", "news headline"]].head(10))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

newspaperDataset.csv:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/260 [00:00<?, ? examples/s]

Total usable articles: 230
Unique incidents: 13
Unique news sources: 26

,Incident,news source,news headline
0,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,জাগো নিউজ ২৪,জুলাই গণঅভ্যুত্থান ইতিহাসের অনন্য ঘটনা: নাহিদ
1,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,সময় সংবাদ,ঐতিহাসিক জুলাই গণ-অভ্যুত্থান দিবস আজ
2,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,বাংলানিউজ২৪,জুলাই গণঅভ্যুত্থান ২০২৪–এর শহীদদের গেজেট প্রকাশ
3,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জুলাই অভ্যুত্থান : যেসব কারণে ফুঁসে উঠেছিল মানুষ
4,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,সমকাল,ক্যাম্পাস থেকেই সূচনা গণঅভ্যুত্থানের
5,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,ইত্তেফাক,কেন অনিবার্য হয়ে উঠেছিল জুলাই গণঅভ্যুত্থান
6,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,বাংলা ট্রিবিউন,জুলাই গণঅভ্যুত্থানের বিজয়: এখন রাষ্ট্র সংস্কা...
7,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,কালের কণ্ঠ,জুলাই অভ্যুত্থান স্মরণে ছাত্রদলের মাসব্যাপী কর...
8,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,যুগান্তর,কোটা সংস্কার আন্দোলন থেকে গণ-অভ্যুত্থান
9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,ঢাকা পোস্ট,"ছাত্র আন্দোলন থেকে গণবিস্ফোরণ, যে কারণে ১৬ বছর..."


# 4. Incident grouping
This shows how many articles and different news portals exist for each incident.

In [8]:
incident_summary = (
    df.groupby("Incident")
      .agg(
          Articles=("news body", "count"),
          Sources=("news source", "nunique")
      )
      .reset_index()
      .sort_values(["Sources", "Articles"], ascending=False)
      .reset_index(drop=True)
)

display(incident_summary)

                                             Incident  Articles  Sources
0   বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...        20       13
1               ‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬)        20       13
2   জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...        16       13
3    শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪)        18       12
4       সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ        19       10
5   উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...        18       10
6   আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...        17       10
7   অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...        20        9
8   ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...        20        9
9          অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪)        19        8
10                   দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬)        18        8
11  ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...        17        8
12           ২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন         8        6


# 5. Pick one article per portal for each incident
If a portal has multiple articles about the same incident, keep its **longest article**.

In [9]:
temp = df.copy()
temp["body_length"] = temp["news body"].str.len()

representatives = (
    temp.sort_values("body_length", ascending=False)
        .drop_duplicates(subset=["Incident", "news source"])
        .reset_index(drop=True)
)

display(
    representatives[
        ["Incident", "news source", "news headline", "body_length"]
    ]
)

,Incident,news source,news headline,body_length
0,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),প্রথম আলো,"ছাত্র–জনতার বিজয়, শেখ হাসিনার বিদায়",11822
1,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,আরটিভি অনলাইন,কোটা সংস্কার আন্দোলন থেকে সরকার পতন,11352
2,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,জাগো নিউজ ২৪,২০২৫ সালে আন্তর্জাতিক অপরাধ ট্রাইব্যুনালে বিচা...,10438
3,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),জাগো নিউজ ২৪,বাংলাদেশে হামের মহামারি এবং একটি জনস্বাস্থ্য চ...,10400
4,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),প্রথম আলো,"জুলাই সনদ ও গণভোট: ঐকমত্য, নাকি চাপিয়ে দেওয়া...",9970
...,...,...,...,...
124,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ইত্তেফাক,ভেঙে দেওয়া হলো অন্তর্বর্তী সরকার,742
125,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,বাংলানিউজ২৪,মানবতাবিরোধী অপরাধ: শেখ হাসিনার মামলার রায় ১৭...,698
126,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),যমুনা টিভি,পদত্যাগ করে দেশ ছেড়েছেন শেখ হাসিনা,670
127,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,দেশ রূপান্তর,খালেদা জিয়ার মৃত্যুতে গুলশানে শোকের ছায়া,269
128,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,বাংলানিউজ২৪,জুলাই গণঅভ্যুত্থান ২০২৪–এর শহীদদের গেজেট প্রকাশ,47


# 6. Create different-newspaper pairs

Only articles from the **same incident** but **different sources** are paired.

Default:
```python
PAIRS_PER_INCIDENT = 2
```
This keeps the notebook practical and balanced.

Use:
```python
PAIRS_PER_INCIDENT = None
```
to evaluate **every possible cross-source pair**.

In [10]:
PAIRS_PER_INCIDENT = 2

all_pairs = []

for incident, group in representatives.groupby("Incident"):
    articles = group.to_dict("records")
    possible_pairs = list(combinations(articles, 2))

    possible_pairs = [
        (a, b)
        for a, b in possible_pairs
        if a["news source"] != b["news source"]
    ]

    random.Random(SEED).shuffle(possible_pairs)

    if PAIRS_PER_INCIDENT is not None:
        possible_pairs = possible_pairs[:PAIRS_PER_INCIDENT]

    for a, b in possible_pairs:
        all_pairs.append({
            "Incident": incident,
            "source_a": a["news source"],
            "headline_a": a["news headline"],
            "body_a": a["news body"],
            "source_b": b["news source"],
            "headline_b": b["news headline"],
            "body_b": b["news body"],
        })

pairs = pd.DataFrame(all_pairs).reset_index(drop=True)
pairs.insert(0, "pair_id", range(1, len(pairs) + 1))

print("Total pairs selected:", len(pairs))

display(
    pairs[
        ["pair_id", "Incident", "source_a", "headline_a", "source_b", "headline_b"]
    ]
)

Total pairs selected: 26

,pair_id,Incident,source_a,headline_a,source_b,headline_b
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ,"কোথায় আছেন ড. মুহাম্মদ ইউনূস, করছেন কী?",আরটিভি অনলাইন,অন্তর্বর্তী সরকারের ১ বছর পূর্তি আজ
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট,"নবীন-প্রবীণে অন্তর্বর্তী সরকার, কার কী পরিচয়?",জাগো নিউজ ২৪,অন্তর্বর্তী সরকারের শপথ বৈধ: আপিল বিভাগ
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,আইএমএফের ঋণশর্ত ভোগান্তি বাড়াচ্ছে,বাংলা ট্রিবিউন,রিজার্ভেও আইএমএফের শর্ত পূরণ করলো বাংলাদেশ
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,আইএমএফের ঋণশর্ত ভোগান্তি বাড়াচ্ছে,সময় সংবাদ,আইএমএফের ঋণের তৃতীয় কিস্তির ১১৫ কোটি ডলার পেল ...
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,মানবতাবিরোধী অপরাধ: এক নজরে শেখ হাসিনাসহ ৩ আসা...,প্রথম আলো,"শেখ হাসিনার বিরুদ্ধে মামলার রায় কবে, জানা যাব..."
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,মানবতাবিরোধী অপরাধ: এক নজরে শেখ হাসিনাসহ ৩ আসা...,বাংলা ট্রিবিউন,আন্তর্জাতিক সংবাদমাধ্যমে শেখ হাসিনার মামলার রায়
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,মাইলস্টোনে বিমান বিধ্বস্ত: ২১ জুলাইকে শিক্ষাপ্...,ঢাকা পোস্ট,বিমান বিধ্বস্তের সময় মাইলস্টোনে চলছিল ক্লাস
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,মাইলস্টোনে বিমান বিধ্বস্ত: ২১ জুলাইকে শিক্ষাপ্...,দেশ রূপান্তর,উত্তরায় প্রশিক্ষণ বিমান বিধ্বস্ত
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জুলাই অভ্যুত্থান : যেসব কারণে ফুঁসে উঠেছিল মানুষ,জাগো নিউজ ২৪,জুলাই গণঅভ্যুত্থান ইতিহাসের অনন্য ঘটনা: নাহিদ
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জুলাই অভ্যুত্থান : যেসব কারণে ফুঁসে উঠেছিল মানুষ,কালের কণ্ঠ,জুলাই অভ্যুত্থান স্মরণে ছাত্রদলের মাসব্যাপী কর...
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,বাতিল হচ্ছে সাইবার নিরাপত্তা আইন,বাংলাদেশ সংবাদ সংস্থা (বাসস),"সাইবার সুরক্ষা অধ্যাদেশ, ২০২৪ প্রণয়নের কাজ চূড়..."
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,বাতিল হচ্ছে সাইবার নিরাপত্তা আইন,প্রথম আলো,সাইবার নিরাপত্তা আইন বাতিল করে সাইবার সুরক্ষা ...
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল,হামের লক্ষণ নিয়ে শিশুর মৃত্যু একশ ছাড়াল,বাংলাদেশ সংবাদ সংস্থা (বাসস),বিগত দুই সরকারের আমলে টিকাদান ব্যাহত হওয়ায় হ...
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা,টিকা বন্ধ করে দেওয়ার পর দেশে হামের ভয়াবহ প্র...,আরটিভি অনলাইন,এ বছর বিশ্বে হামে মৃত্যুতে শীর্ষে বাংলাদেশ
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,সোমবার থেকে সব বিশ্ববিদ্যালয় বন্ধ ঘোষণা,এনটিভি অনলাইন,জ্বালানি সাশ্রয়ে সব বিশ্ববিদ্যালয়ে ছুটি শুরু...
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,সোমবার থেকে সব বিশ্ববিদ্যালয় বন্ধ ঘোষণা,যুগান্তর,সোমবার থেকে সব বিশ্ববিদ্যালয় বন্ধ
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,দৈনিক ইত্তেফাক,একীভূত হতে পারে সংকটে থাকা ছোট ব্যাংকগুলো: গভর্নর,সমকাল,ইসলামী ব্যাংকের পর্ষদ ভেঙে দেওয়া হচ্ছে
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,যুগান্তর,এস আলমের মতো ব্যাংক লুটেরা পৃথিবীতে নেই,ঢাকা পোস্ট,"এস আলমের বিরুদ্ধে অ্যাকশন, যেখানে হাত দেওয়ার স..."
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪,জুলাই গণঅভ্যুত্থান দিবস আজ,যমুনা টিভি,পদত্যাগ করে দেশ ছেড়েছেন শেখ হাসিনা
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট,খুলনায় আ.লীগের পতনের ঘণ্টা বাজে ৪ আগস্ট,এখন টিভি,শেখ হাসিনার পদত্যাগ-দেশ ছাড়ার খবরে গুরুত্ব দি...
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),খালেদা জিয়ার মৃত্যুতে উপদেষ্টা পরিষদের বিশেষ ...,আজকের পত্রিকা,"খালেদা জিয়ার মৃত্যুতে ৩ দিনের রাষ্ট্রীয় শোক,..."
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),খালেদা জিয়ার মৃত্যুতে উপদেষ্টা পরিষদের বিশেষ ...,সময় সংবাদ,বেগম জিয়ার মৃত্যু: তিন দিনের রাষ্ট্রীয় শোক চলছে
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক,ত্রয়োদশ সংসদ নির্বাচনে ভোটার উপস্থিতি ৬০.৬৯ শ...,আজকের পত্রিকা,জাতীয় সংসদ নির্বাচন ২০২৬: আসনভিত্তিক আপডেট
23,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস),"নির্বাচনে বিএনপি ৪৯.৯৭ শতাংশ, জামায়াত ৩১.৭৬ শ...",আজকের পত্রিকা,জাতীয় সংসদ নির্বাচন ২০২৬: আসনভিত্তিক আপডেট
24,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,"জুলাই সনদ রক্তের বিনিময়ে তৈরি, সরকার গণভোটের ...",ঢাকা পোস্ট,"গণভোট ২০২৬: জুলাই জাতীয় সনদ বাস্তবায়ন—কী, কে..."
25,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,"জুলাই সনদ রক্তের বিনিময়ে তৈরি, সরকার গণভোটের ...",বাংলাদেশ সংবাদ সংস্থা (বাসস),গণভোটের ফলাফলে সংশোধনী গেজেট প্রকাশ করেছে ইসি

# 7. One common prompt for all models

In [11]:
MAX_BODY_CHARS = 4500

def clean_text(text):
    return re.sub(r"\s+", " ", str(text)).strip()

def make_prompt(row):
    body_a = clean_text(row["body_a"])[:MAX_BODY_CHARS]
    body_b = clean_text(row["body_b"])[:MAX_BODY_CHARS]

    return f"""
তুমি একজন নিরপেক্ষ বাংলা সংবাদ বিশ্লেষক।

নিচে একই ঘটনার ওপর দুইটি ভিন্ন সংবাদমাধ্যমের প্রতিবেদন দেওয়া হয়েছে।
শুধু প্রদত্ত লেখার ভিত্তিতে তুলনা করবে। কোনো অপ্রমাণিত উদ্দেশ্য বা রাজনৈতিক পক্ষপাত অনুমান করবে না।

ঘটনা:
{row['Incident']}

সংবাদমাধ্যম A: {row['source_a']}
শিরোনাম A: {row['headline_a']}
প্রতিবেদন A:
{body_a}

সংবাদমাধ্যম B: {row['source_b']}
শিরোনাম B: {row['headline_b']}
প্রতিবেদন B:
{body_b}

একই ঘটনাকে দুই সংবাদমাধ্যম কীভাবে ভিন্নভাবে উপস্থাপন করেছে তা তুলনা করো।

ঠিক এই ৬টি অংশে উত্তর দাও:

A-এর উপস্থাপন:
B-এর উপস্থাপন:
সাদৃশ্য:
ভিন্ন গুরুত্ব/ফ্রেমিং:
টোন ও আলোচিত ব্যক্তি/পক্ষ:
সারসংক্ষেপ:

প্রতিটি অংশ ১-২টি সংক্ষিপ্ত বাক্যে লিখবে। শুধু বাংলায় উত্তর দেবে।
""".strip()


# 8. Gemini reference generation
Gemini is treated as the **reference** according to the faculty instruction.

In [12]:
from google import genai
from google.genai import types

GEMINI_MODEL = "gemini-3.1-flash-lite"

GEMINI_API_KEY = getpass.getpass("Gemini API key: ").strip()
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

def gemini_answer(prompt):
    response = gemini_client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(max_output_tokens=700)
    )
    return response.text.strip()

Gemini API key: ··········

In [13]:
gemini_outputs = []

for _, row in tqdm(pairs.iterrows(), total=len(pairs), desc="Gemini"):
    gemini_outputs.append(gemini_answer(make_prompt(row)))

results = pairs.copy()
results["Gemini Reference"] = gemini_outputs

print("Gemini reference generation complete.")
display(
    results[
        ["pair_id", "Incident", "source_a", "source_b", "Gemini Reference"]
    ]
)

Gemini:   0%|          | 0/26 [00:00<?, ?it/s]

Gemini reference generation complete.

,pair_id,Incident,source_a,source_b,Gemini Reference
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ,আরটিভি অনলাইন,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট,জাগো নিউজ ২৪,প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষ...
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,বাংলা ট্রিবিউন,আপনার অনুরোধ অনুযায়ী দুটি সংবাদপত্রের প্রতিবেদ...
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,সময় সংবাদ,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে...
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,প্রথম আলো,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে নিরপেক্ষ বিশ্...
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,বাংলা ট্রিবিউন,নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবে...
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,ঢাকা পোস্ট,নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবে...
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,দেশ রূপান্তর,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে...
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জাগো নিউজ ২৪,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে...
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,কালের কণ্ঠ,নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবে...
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,বাংলাদেশ সংবাদ সংস্থা (বাসস),প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে...
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,প্রথম আলো,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল,বাংলাদেশ সংবাদ সংস্থা (বাসস),প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষ...
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা,আরটিভি অনলাইন,আপনার অনুরোধ অনুযায়ী সংবাদমাধ্যম দুটির প্রতিবে...
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,এনটিভি অনলাইন,আপনার অনুরোধ অনুযায়ী প্রদত্ত প্রতিবেদনের ভিত্ত...
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,যুগান্তর,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,দৈনিক ইত্তেফাক,সমকাল,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে নিরপেক্ষ বিশ্...
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,যুগান্তর,ঢাকা পোস্ট,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪,যমুনা টিভি,প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষ...
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট,এখন টিভি,আপনার অনুরোধ অনুযায়ী প্রদত্ত প্রতিবেদনের ভিত্ত...
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবে...
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),সময় সংবাদ,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক,আজকের পত্রিকা,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
23,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্...
24,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,ঢাকা পোস্ট,নিরপেক্ষ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুট...
25,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,বাংলাদেশ সংবাদ সংস্থা (বাসস),নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবে...

# 9. Qwen zero-shot

In [14]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

QWEN_MODEL = "Qwen/Qwen3-1.7B"

quantization = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

qwen_tokenizer = AutoTokenizer.from_pretrained(QWEN_MODEL)
qwen_model = AutoModelForCausalLM.from_pretrained(
    QWEN_MODEL,
    quantization_config=quantization,
    device_map="auto"
).eval()

def qwen_answer(prompt):
    messages = [{"role": "user", "content": prompt}]

    text = qwen_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False
    )

    inputs = qwen_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=6000
    )

    device = next(qwen_model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.inference_mode():
        output = qwen_model.generate(
            **inputs,
            max_new_tokens=700,
            do_sample=False
        )

    new_tokens = output[0][inputs["input_ids"].shape[1]:]
    return qwen_tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

model.safetensors.index.json:   0%|          | 0.00/25.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [15]:
qwen_outputs = []

for _, row in tqdm(results.iterrows(), total=len(results), desc="Qwen"):
    qwen_outputs.append(qwen_answer(make_prompt(row)))

results["Qwen Zero-Shot"] = qwen_outputs

print("Qwen zero-shot complete.")
display(
    results[
        ["pair_id", "Incident", "source_a", "source_b", "Qwen Zero-Shot"]
    ]
)

Qwen:   0%|          | 0/26 [00:00<?, ?it/s]

Qwen zero-shot complete.

,pair_id,Incident,source_a,source_b,Qwen Zero-Shot
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ,আরটিভি অনলাইন,য়ারিতে অনুষ্ঠিত হবে। এর পর সরকার নির্বাচন কমি...
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট,জাগো নিউজ ২৪,্রান্ত রায়ের বিরুদ্ধে একটি আপিল করা হয়েছে। এ...
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,বাংলা ট্রিবিউন,"�, বাংলাদেশ ব্যাংক এর রিজার্ভ সংরক্ষণ প্রতিদিন..."
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,সময় সংবাদ,ালে বাংলাদেশ ব্যাংক এর রিজার্ভ ছিল ২৫.৫ বিলিয়...
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,প্রথম আলো,রাজসাক্ষ্য) হিসেবে সাক্ষ্য দিয়েছেন। এ মামলার ...
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,বাংলা ট্রিবিউন,নের ঘটনায় মৃত্যুদণ্ড দেওয়া হয়েছে’ শিরোনামে ...
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,ঢাকা পোস্ট,"িষয়ে একটি স্থানীয় বাসিন্দা বলেন, এ ঘটনায় স্..."
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,দেশ রূপান্তর,�ক্ষিপ্ত করে দেখেছি। একটি বিমান একটি বাস থেকে ...
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জাগো নিউজ ২৪,"একটি সম্প্রচার উপদেষ্টা বলেছেন, একটি সম্প্রচার..."
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,কালের কণ্ঠ,"্তিতে বলা হয়েছিল, ছাত্রদল একটি মাসব্যাপী কর্ম..."
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,বাংলাদেশ সংবাদ সংস্থা (বাসস),"�ুরক্ষা অধ্যাদেশ, ২০২৪ প্রণয়নের কাজ চূড়ান্ত ..."
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,প্রথম আলো,ভেম্বর এ সম্মেলনে আইন মন্ত্রণালয়ের উপদেষ্টা আ...
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল,বাংলাদেশ সংবাদ সংস্থা (বাসস),াক্তারদের ছুটি বাতিল হয়েছে। এ কারণে স্বাস্থ্য...
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা,আরটিভি অনলাইন,"অনুযায়ী, বাংলাদেশে হামের মৃত্যু হার প্রায় ২০..."
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,এনটিভি অনলাইন,A-এর উপস্থাপন:\nপ্রদত্ত প্রতিবেদন একটি সামাজিক...
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,যুগান্তর,A-এর উপস্�থাপন:\nবিদ্যুৎ ও জ্বালানি সাশ্রয়ে ব...
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,দৈনিক ইত্তেফাক,সমকাল,�্যাংক বাংলাদেশের পরিচালনা পর্ষদ ভেঙে দেওয়ার ...
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,যুগান্তর,ঢাকা পোস্ট,ত্বে সরকার সম্মেলনে এস আলম গ্রুপের মালিকেরা বি...
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪,যমুনা টিভি,A-এর উপস্থাপন:\nজুলাই গণঅভ্যুত্থান দিবস আজ। ছা...
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট,এখন টিভি,�ায় সব স্থানে আন্তর্জাতিক সংবাদমাধ্যমের চোখ এ...
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,িবসে। সেদিন তিনি খুব উৎফুল্ল ছিলেন। আমার সাথে ...
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),সময় সংবাদ,A-এর উপস্থাপন:\nবাসস সংবাদ সংস্থা এর প্রতিবেদন...
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক,আজকের পত্রিকা,"A-এর উপস্থাপন:\nইসি সূত্রে জানা গেছে, ত্রয়োদশ..."
23,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,A-এর উপস্থাপন:\nবাসস সংবাদমাধ্যমে নির্বাচনের ফ...
24,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,ঢাকা পোস্ট,ে সম্পূর্ণ রাষ্ট্রীয় সম্প্রদায়ের মধ্যে স্থান...
25,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,বাংলাদেশ সংবাদ সংস্থা (বাসস),ুষ্ঠিত গণভোটের ফলাফল প্রাপ্ত হয়েছে। এ সংশোধনী...

In [16]:
del qwen_model
gc.collect()
torch.cuda.empty_cache()


# 10. Gemma zero-shot

Before running:
1. Open `google/gemma-3-4b-it` on Hugging Face.
2. Accept the Gemma license.
3. Paste your Hugging Face token.

In [17]:
from huggingface_hub import login
from transformers import AutoProcessor, Gemma3ForConditionalGeneration

GEMMA_MODEL = "google/gemma-3-4b-it"

HF_TOKEN = getpass.getpass("Hugging Face token: ").strip()
login(token=HF_TOKEN)

gemma_processor = AutoProcessor.from_pretrained(
    GEMMA_MODEL,
    token=HF_TOKEN
)

gemma_model = Gemma3ForConditionalGeneration.from_pretrained(
    GEMMA_MODEL,
    token=HF_TOKEN,
    quantization_config=quantization,
    device_map="auto"
).eval()

def gemma_answer(prompt):
    messages = [
        {
            "role": "user",
            "content": [{"type": "text", "text": prompt}]
        }
    ]

    inputs = gemma_processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
        truncation=True,
        max_length=6000
    )

    device = next(gemma_model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}
    input_length = inputs["input_ids"].shape[1]

    with torch.inference_mode():
        output = gemma_model.generate(
            **inputs,
            max_new_tokens=700,
            do_sample=False
        )

    new_tokens = output[0][input_length:]
    return gemma_processor.decode(new_tokens, skip_special_tokens=True).strip()

Hugging Face token: ··········

processor_config.json:   0%|          | 0.00/70.0 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/1.61k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 33.4MB

tokenizer.json: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

In [18]:
gemma_outputs = []

for _, row in tqdm(results.iterrows(), total=len(results), desc="Gemma"):
    gemma_outputs.append(gemma_answer(make_prompt(row)))

results["Gemma Zero-Shot"] = gemma_outputs

print("Gemma zero-shot complete.")
display(
    results[
        ["pair_id", "Incident", "source_a", "source_b", "Gemma Zero-Shot"]
    ]
)

Gemma:   0%|          | 0/26 [00:00<?, ?it/s]

[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Deprecated: `processor.image_token` will switch from returning `tokenizer.image_token` to `tokenizer.boi_token` in v5.11.
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
[transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

Gemma zero-shot complete.

,pair_id,Incident,source_a,source_b,Gemma Zero-Shot
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ,আরটিভি অনলাইন,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর একটি ত...
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট,জাগো নিউজ ২৪,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,বাংলা ট্রিবিউন,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ...",যুগান্তর,সময় সংবাদ,এখানে যুগান্তর ও সময়সংবাদ - এই দুটি সংবাদমাধ্য...
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,প্রথম আলো,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হ...,সময় সংবাদ,বাংলা ট্রিবিউন,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,ঢাকা পোস্ট,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ...
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটন...,প্রথম আলো,দেশ রূপান্তর,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ...
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,জাগো নিউজ ২৪,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২...,এনটিভি অনলাইন,কালের কণ্ঠ,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ...
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,বাংলাদেশ সংবাদ সংস্থা (বাসস),এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর ওপর ভি...
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা...,যুগান্তর,প্রথম আলো,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল,বাংলাদেশ সংবাদ সংস্থা (বাসস),এখানে সমকাল (A) এবং বাসস (B) সংবাদমাধ্যমের প্র...
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা,আরটিভি অনলাইন,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর একটি ব...
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,এনটিভি অনলাইন,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ...
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের ...,জাগো নিউজ ২৪,যুগান্তর,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,দৈনিক ইত্তেফাক,সমকাল,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুট...,যুগান্তর,ঢাকা পোস্ট,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪,যমুনা টিভি,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন পর্যালোচনার...
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট,এখন টিভি,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),সময় সংবাদ,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক,আজকের পত্রিকা,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
23,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
24,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,ঢাকা পোস্ট,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...
25,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক,বাংলাদেশ সংবাদ সংস্থা (বাসস),এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্...

In [19]:
del gemma_model
del gemma_processor
gc.collect()
torch.cuda.empty_cache()


# 11. Show all model outputs together
This is the main qualitative comparison table.

In [20]:
pd.set_option("display.max_colwidth", 250)
pd.set_option("display.max_rows", None)

display(
    results[
        [
            "pair_id",
            "Incident",
            "source_a",
            "source_b",
            "Gemini Reference",
            "Qwen Zero-Shot",
            "Gemma Zero-Shot"
        ]
    ]
)

,pair_id,Incident,source_a,source_b,Gemini Reference,Qwen Zero-Shot,Gemma Zero-Shot
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ,আরটিভি অনলাইন,"একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি ড. মুহাম্মদ ইউনূসের ক্ষমতা হস্তান্তরের পরবর্তী ব্যক্তিগত জীবন, তার দৈনন্দিন রুটিন এবং ভবিষ্যৎ পরিকল্পনার ওপর আলোকপাত...",য়ারিতে অনুষ্ঠিত হবে। এর পর সরকার নির্বাচন কমিশন এবং সরকার মন্ত্রিসভা এবং সরকার স্বৈরশাসন এবং সরকার জাতীয় সংসদ নির্বাচন প্রক্রিয়ার মধ্য দিয়ে সব খাতে সম্মিলিত হবে। এর পর সরকার স্বৈরশাসন এবং সরকার জাতীয় সংসদ নির্বাচন প্রক্রিয়ার মধ্য দিয়ে সব খ...,"এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর একটি তুলনামূলক বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nড. মুহাম্মদ ইউনূস যমুনায় পরিবার ও ভবিষ্যৎ পরিকল্পনা নিয়ে সময় কাটাচ্ছেন, যা তার ব্যক্তিগত জীবন এবং সাংগঠনিক কাজকর্মের উপর বেশি জোর দিচ্ছে। তিনি পাসপোর্ট ..."
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট,জাগো নিউজ ২৪,"প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি ৮ আগস্ট ২০২৪-এ অন্তর্বর্তী সরকার গঠনের মুহূর্ত ও নবনিযুক্ত উপদেষ্টাদের পরিচয় তুলে ধরার ওপর আলোকপাত করেছে। এতে উপদেষ্টাদের ব্যক্তিগত জীবন, কর্মজীবন ...",্রান্ত রায়ের বিরুদ্ধে একটি আপিল করা হয়েছে। এ আপিল বিভাগের আইনজীবী আইন বিভাগের অধ্যাপক ড. আসিফ নজরুল এবং আইন বিভাগের অধ্যাপক ড. আসিফ নজরুল একজন আইনজীবী এবং সাবেক অ্যাটর্নি জেনারেল হাসান আরিফ এবং আইন বিভাগের অধ্যাপক ড. আসিফ নজরুল একজন আইনজীবী এবং...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ওপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nঢাকা পোস্ট প্রতিবেদনটিতে অন্তর্বর্তীকালীন সরকারের উপদেষ্টাদের পরিচয় এবং তাদের পটভূমি সম্পর্কে বিস্তারিত তথ্য দিয়েছে। এখানে ড. ইউনূসে...
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর,বাংলা ট্রিবিউন,আপনার অনুরোধ অনুযায়ী দুটি সংবাদপত্রের প্রতিবেদনের তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nযুগান্তর আইএমএফ-এর শর্তপূরণকে সাধারণ মানুষের জীবনযাত্রার ব্যয় বৃদ্ধি ও অর্থনৈতিক ভোগান্তির কারণ হিসেবে উপস্থাপন করেছে।\n\n**B-এর উপস্থাপন:...,"�, বাংলাদেশ ব্যাংক এর রিজার্ভ সংরক্ষণ প্রতিদিন প্রায় ২০০ কোটি ডলার হিসাবে হারিয়ে যায়। এ প্রায় ২০০ কোটি ডলার হিসাবে বাংলাদেশ ব্যাংক এর রিজার্ভ সংরক্ষণ প্রতিদিন হারিয়ে যায়। এ প্রায় ২০০ কোটি ডলার হিসাবে বাংলাদেশ ব্যাংক এর রিজার্ভ সংরক্ষণ প্রত...",এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ওপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nযুগান্তর মূলত আইএমএফের ঋণের শর্তগুলোর নেতিবাচক প্রভাব এবং সরকারের ওপর চাপ নিয়ে একটি সমালোচনামূলক প্রতিবেদন দিয়েছে। এখানে অর্থনৈতিক স...
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর,সময় সংবাদ,প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nযুগান্তর আইএমএফের ঋণকে একটি শোষণমূলক ব্যবস্থা হিসেবে চিহ্নিত করে এর শর্তগুলোর নেতিবাচক অর্থনৈতিক প্রভাব ও সাধারণ মানুষের ভোগান্তির ওপর গুরুত্বারোপ করেছে।\n\n**B-এর উ...,"ালে বাংলাদেশ ব্যাংক এর রিজার্ভ ছিল ২৫.৫ বিলিয়ন ডলার। এ বৃহস্পতিবার মুখপাত্র বলেন, এ রিজার্ভ বাড়ানোর প্রস্তাব করা হয়েছিল বাংলাদেশ ব্যাংকের মুখপাত্র এবং বাংলাদেশ ব্যাংকের সাথে সামঞ্জন্য প্রতিষ্ঠানগুলোর মাধ্যমে এ রিজার্ভ বাড়ানোর প্রস্তাব করা হয়...","এখানে যুগান্তর ও সময়সংবাদ - এই দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্য বিশ্লেষণ করে উত্তর দেওয়া হলো:\n\nA-এর উপস্থাপন:\nযুগান্তর আইএমএফের ঋণের শর্তগুলোর নেতিবাচক প্রভাব এবং সরকারের ওপর চাপ নিয়ে বিশেষভাবে সরব। এখানে অর্থনৈতিক সংকট, মুদ্রাস্..."
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ,প্রথম আলো,"প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে নিরপেক্ষ বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** প্রতিবেদনটি মামলার বিস্তারিত প্রেক্ষাপট, সাক্ষীদের বিবরণ, নথিপত্রের পরিসংখ্যান এবং যুক্তিতর্ক উপস্থাপনের প্রক্রিয়ার ওপর অধিক গুরুত্ব দিয়েছে।\n\n**B-এর উপস্থ...",রাজসাক্ষ্য) হিসেবে সাক্ষ্য দিয়েছেন। এ মামলার প্রসিকিউশন পক্ষে যুক্তিতর্ক শেষ হয়েছে। এ মামলার রায় কবে দেওয়া হবে আজ বৃহস্পতিবার। এ মামলার রায় কবে দেওয়া হবে আজ বৃহস্পতিবার। এ মামলার রায় কবে দেওয়া হবে আজ বৃহস্পতিবার। এ মামলার রায় কবে দেওয়া ...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ভিত্তিতে একটি তুলনামূলক বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nসময় সংবাদ প্রতিবেদনটি মামলাটির অগ্রগতি এবং সাক্ষ্যপ্রমাণ সম্পর্কিত বিস্তারিত তথ্য দিয়েছে। এটি আসামিদের পলাতক থাকার বিষয়টি এবং ত...
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ,বাংলা ট্রিবিউন,"নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nসময় সংবাদ মূলত মামলার বিচারিক প্রক্রিয়া, শুনানির সময়রেখা এবং প্রসিকিউশনের দাবির ওপর ভিত্তি করে একটি তথ্যবহুল প্রতিবেদন উপস্থাপন করেছে...","নের ঘটনায় মৃত্যুদণ্ড দেওয়া হয়েছে’ শিরোনামে লাইভ করছে। এক নজরে শেখ হাসিনাসহ তিনজনের মামলা আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল-১ এ প্রসিকিউশন পক্ষে যুক্তিতর্ক শেষ হয়েছে। এর পর দিন মামলার রায় কবে দেয়া হবে, তা আগামী কাল বলে জানানো হবে। এর মধ্যে মামল...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের উপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nসময় সংবাদে ঘটনার বিস্তারিত বিবরণ দেওয়া হয়েছে, যেখানে মামলার অগ্রগতি, সাক্ষীদের বক্তব্য, এবং যুক্তিতর্ক উপস্থাপিত হয়েছে। এটি একটি নি..."
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো,ঢাকা পোস্ট,"নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nসংবাদমাধ্যম A দুর্ঘটনা-পরবর্তী পরিস্থিতি, ভুক্তভোগী পরিবারগুলোর দুঃখ-দুর্দশা এবং সরকারি সুযোগ-সুবিধা ও স্বীকৃতির দাবির ওপর আলোকপাত কর...","িষয়ে একটি স্থানীয় বাসিন্দা বলেন, এ ঘটনায় স্কুল শাখায় প্রথম শ্রেণি থেকে সপ্তম শ্রেণি পর্যন্ত ক্লাস চলছিল। এ ঘটনায় স্কুল শাখায় প্রথম শ্রেণি থেকে সপ্তম শ্রেণি পর্যন্ত ক্লাস চলছিল। এ ঘটনায় স্কুল শাখায় প্রথম শ্রেণি থেকে সপ্তম শ্রেণি পর্যন্ত ক্...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ভিন্ন ভিন্ন উপস্থাপনা তুলে ধরা হলো:\n\nA-এর উপস্থাপন: প্রথম আলো বিস্তারিতভাবে হতাহতদের পরিবারের দুর্দশা, তাদের দাবি এবং ক্ষোভের কথা তুলে ধরেছে। এটি দুর্ঘটনার শিকার হওয়া শিক্ষার্থীদের এবং তাদের অভিভাবক..."
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো,দেশ রূপান্তর,"প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** প্রতিবেদনটি দুর্ঘটনার কয়েক মাস পরবর্তী প্রেক্ষাপটে ভুক্তভোগী পরিবারগুলোর সংবাদ সম্মেলন, তাদের দাবি-দাওয়া এবং মানসিক ট্রমার ওপর আলোকপাত করেছে।\n\n**B-এর উপস্থাপন:** প্...",�ক্ষিপ্ত করে দেখেছি। একটি বিমান একটি বাস থেকে উড়িয়ে গেল। এটি বিমানবাহিনীর এফ-৭ বিজেআই মডেলের একটি প্রশিক্ষণ বিমান। এটি বিমানবাহিনীর একটি প্রশিক্ষণ বিমান ছিল যেন একটি বাস থেকে উড়িয়ে গেল। এটি বিমানবাহিনীর একটি প্রশিক্ষণ বিমান ছিল যেন একটি বাস থ...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ভিন্ন ভিন্ন উপস্থাপনা তুলে ধরা হলো:\n\nA-এর উপস্থাপন: প্রথম আলো বিস্তারিতভাবে ঘটনার বিবরণ দিয়েছে এবং হতাহত ব্যক্তিদের পরিবারের আবেগঘন প্রতিক্রিয়া ও দাবিগুলো তুলে ধরেছে। এটি দুর্ঘটনার শিকার হওয়া শিক্ষা...
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন,জাগো নিউজ ২৪,"প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটিতে জুলাই অভ্যুত্থানের পেছনের কারণ হিসেবে গত ১৬ বছরের রাজনৈতিক প্রেক্ষাপট, মানবাধিকার লঙ্ঘন, দুর্নীতি ও প্রশাসনিক অব্যবস্থাপনাকে বিশ্লেষণ করা হয়েছে।\n\n**B...","একটি সম্প্রচার উপদেষ্টা বলেছেন, একটি সম্প্রচার উপদেষ্টা মো. নাহিদ ইসলাম বলেছেন, জুলাই গণঅভ্যুত্থান বাংলাদেশের ইতিহাসের এক অনন্য ঘটনা। একটি সম্প্রচার উপদেষ্টা বলেছেন, একটি সম্প্রচার উপদেষ্টা মো. নাহিদ ইসলাম বলেছেন, জুলাই গণঅভ্যুত্থান বাংলাদেশের ইত...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ভিত্তিতে একটি তুলনামূলক বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nএনটিভি অনলাইন একটি বিস্তারিত এবং ঘটনাবহুল প্রতিবেদন দিয়েছে, যেখানে ২০২৪ সালের জুলাইয়ের গণঅভ্যুত্থানের পেছনের কারণ, রাজনৈতিক প্রে..."
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন,কালের কণ্ঠ,"নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি জুলাই গণঅভ্যুত্থানের পেছনের দীর্ঘমেয়াদী রাজনৈতিক, অর্থনৈতিক ও সামাজিক কারণসমূহ বিশ্লেষণ করে ঘটনার একটি সামগ্রিক ব্যাখ্যা ...","্তিতে বলা হয়েছিল, ছাত্রদল একটি মাসব্যাপী কর্মসূচি ঘোষণা করেছে যাতে দুঃশাসনের বিরুদ্ধে ছাত্র-জনতার দীর্ঘ ধারাবাহিক লড়াইয়ের বীরোচিত বিজয়ের দ্বিতীয় বর্ষপূর্তি উদযাপনে এই উদ্যোগ নেওয়া হয়েছে। ছাত্রদল একটি মাসব্যাপী কর্মসূচি ঘোষণা করেছে যাতে দুঃ...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ভিন্ন ভিন্ন উপস্থাপনা এবং তাদের মধ্যেকার সাদৃশ্য, ভিন্নতা, টোন এবং আলোচিত ব্যক্তি/পক্ষের বিষয়গুলো তুলে ধরা হলো:\n\nA-এর উপস্থাপন:\nএনটিভি অনলাইন একটি বিস্তারিত এবং সমালোচনামূলক প্রতিবেদন দিয়েছে। এখানে..."
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর,বাংলাদেশ সংবাদ সংস্থা (বাসস),"প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nযুগান্তর প্রধান উপদেষ্টার কার্যালয়ের ব্রিফিংয়ের ওপর ভিত্তি করে আইনটি বাতিলের সিদ্ধান্ত, এর প্রেক্ষাপট এবং সরকারের নেওয়া অন্যান্য উন্নয়নমূলক উদ্যোগের বিস্তারিত বিবরণ ...","�ুরক্ষা অধ্যাদেশ, ২০২৪ প্রণয়নের কাজ চূড়ান্ত পর্যায়ে রয়েছে। এ আইন সাইবার নিরাপত্তা আইন বাতিল হলেও সাইবার অপরাধ প্রতিরোধে নতুন একটি আইন করবে সরকার। এ আইন বাতিল হলেও সাইবার অপরাধ প্রতিরোধে নতুন একটি আইন করবে সরকার। এ আইন বাতিল হলেও সাইবার অপরাধ ...",এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর ওপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nযুগান্তর মূলত সাইবার নিরাপত্তা আইন বাতিলের পেছনের রাজনৈতিক প্রেক্ষাপট এবং এর সম্ভাব্য প্রভাবের ওপর জোর দিয়েছে। অন্তর্বর্তী সরকারের পদক্ষেপে মামলাগু...
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর,প্রথম আলো,একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** যুগান্তর আইন বাতিলের খবরের পাশাপাশি একই বৈঠকে আলোচিত ওষুধ বিষয়ক টাস্কফোর্স এবং মুজিববর্ষের ব্যয় নিয়ে শ্বেতপত্র প্রকাশের মতো অতিরি...,"ভেম্বর এ সম্মেলনে আইন মন্ত্রণালয়ের উপদেষ্টা আসিফ নজরুল বলেন, এ আইন বাতিল হওয়ার সঙ্গে সঙ্গে সাইবার সুরক্ষা আইন নামে একটি আইন করা হবে। এ আইন বাতিল হওয়ার সঙ্গে সঙ্গে সাইবার সুরক্ষা আইন হচ্ছে সাইবার নিরাপত্তা আইন বাতিল করে সাইবার সুরক্ষা আইন হচ্ছে...",এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ভিত্তিতে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nযুগান্তর মূলত আইন বাতিলের পেছনের রাজনৈতিক প্রেক্ষাপট এবং এর ফলে সৃষ্ট সামাজিক প্রভাবের ওপর জোর দিয়েছে। এখানে অন্তর্বর্তী সরকারের উপদেষ্টা ...
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল,বাংলাদেশ সংবাদ সংস্থা (বাসস),"প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nসমকাল মূলত তথ্য ও পরিসংখ্যানের ওপর ভিত্তি করে সংক্রমণের বিস্তৃতি, স্বাস্থ্য অধিদপ্তরের কার্যক্রম এবং বিভিন্ন অঞ্চলের হাসপাতালের হালনাগাদ পরিস্থিতির ওপর আলোকপাত...","াক্তারদের ছুটি বাতিল হয়েছে। এ কারণে স্বাস্থ্য অধিদপ্তর এবং জেলা স্বাস্থ্য বিভাগের স্বাস্থ্যকর্মকর্তারা জানান, শিশুদের নিয়মিত টিকাদান কর্মসূচিতে বড় ধরনের ঘাটতি হয়েছে। এ ঘাটতি দুই সরকারের আমলে হামের সংক্রমণ বৃদ্ধির প্রধান কারণ হয়েছে। এ ঘাটতি ক...","এখানে সমকাল (A) এবং বাসস (B) সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ভিত্তিতে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nসমকাল হামের প্রাদুর্ভাবের একটি বিস্তারিত চিত্র তুলে ধরেছে, যেখানে রোগীর সংখ্যা, মৃত্যুর হার, এবং ঝুঁকির এলাকাগুলো স্পষ্ট..."
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা,আরটিভি অনলাইন,আপনার অনুরোধ অনুযায়ী সংবাদমাধ্যম দুটির প্রতিবেদনের তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি দেশের অভ্যন্তরে টিকাদান কর্মসূচিতে বিপর্যয় এবং রাজনৈতিক পরিবর্তনের পর টিকা সংগ্রহ প্রক্রিয়ায় পরিবর্তনকে প্রাদুর্ভাবের প্রধান ...,"অনুযায়ী, বাংলাদেশে হামের মৃত্যু হার প্রায় ২০ শতাংশ এবং শিশুদের মধ্যে এটি হার ছিল ৯ শতাংশ। এ সংখ্যা বাংলাদেশের সর্বাধিক মৃত্যু হার ছিল সাল ২০২৪ সালের মধ্যে। এ সংখ্যা বাংলাদেশের সর্বাধিক মৃত্যু হার ছিল সাল ২০২৪ সালের মধ্যে। এ সংখ্যা বাংলাদেশের সর...",এখানে দুটি সংবাদমাধ্যমের প্রতিবেদনগুলোর একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nসংবাদমাধ্যম A হামের প্রাদুর্ভাবের কারণ হিসেবে টিকাদান কর্মসূচিতে বিপর্যয় এবং রাজনৈতিক পটপরিবর্তনের কথা বলছে। এটি একটি নির্দিষ্ট ঘটনার (রুহির মৃত্যু) মাধ্যমে ব্যক্...
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪,এনটিভি অনলাইন,আপনার অনুরোধ অনুযায়ী প্রদত্ত প্রতিবেদনের ভিত্তিতে বিশ্লেষণটি নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** জাগো নিউজ ২৪ প্রধানমন্ত্রী তারেক রহমানের নির্দেশনার কথা উল্লেখ করেছে এবং ইউজিসির ভূমিকা ও প্রক্রিয়াগত বিষয়ে বিশদ আলোকপাত করেছে।\n\n**B-এর উপস্থাপন:...,A-এর উপস্থাপন:\nপ্রদত্ত প্রতিবেদন একটি সামাজিক স্থানে বিশ্ববিদ্যালয় বন্ধ ঘোষণা করার সিদ্ধান্ত নিয়েছে সরকার। এটি বিশ্ববিদ্যালয়গুলোর সব পাবলিক ও প্রাইভেট কর্মকর্তাদের বিদ্যুৎ ও জ্বালানি সাশ্রয়ী ও দায়িত্বশীল অচরণ নিশ্চিত করতে প্রয়োজন। এটি বিশ্...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে ঘটনার ভিন্ন ভিন্ন উপস্থাপনা তুলে ধরা হলো:\n\nA-এর উপস্থাপন: জাগো নিউজ ২৪ সংবাদমাধ্যমটি প্রধানমন্ত্রীর নির্দেশের ওপর ভিত্তি করে ঘটনাটি তুলে ধরেছে। এখানে প্রধানমন্ত্রীর সিদ্ধান্তকে প্রাধান্য দেওয়া হয়েছে এবং ই...
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪,যুগান্তর,"একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** জাগো নিউজ ২৪ ঘটনাটিকে বিস্তারিতভাবে তুলে ধরেছে, যেখানে বিশ্ববিদ্যালয়ের ছুটির প্রশাসনিক প্রক্রিয়া এবং ইউজিসির ভূমিকা ও পরিসংখ্যানে...",A-এর উপস্�থাপন:\nবিদ্যুৎ ও জ্বালানি সাশ্রয়ে বিশ্ববিদ্যালয়গুলো বন্ধ ঘোষণা করা হয়েছে। প্রধানমন্ত্রীর নির্দেশনায় ঈদুল ফিতরের ছুটি পর্যন্ত বিশ্ববিদ্যালয়গুলো বন্ধ থাকবে। এ সংক্রান্ত নির্দেশনা শিক্ষা মন্ত্রণালয় জারি করেছে।\n\nB-এর উপস্থাপন:\nবিদ্...,"এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের উপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nজাগো নিউজ ২৪-এ প্রধানমন্ত্রীর নির্দেশের উপর জোর দেওয়া হয়েছে, যা এই সিদ্ধান্তের পেছনের রাজনৈতিক প্রেক্ষাপটকে তুলে ধরে। এছাড়াও, ইউজিসি..."
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,দৈনিক ইত্তেফাক,সমকাল,"প্রদত্ত প্রতিবেদন দুটির ভিত্তিতে নিরপেক্ষ বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি সামগ্রিকভাবে ব্যাংকিং খাতের তারল্য সংকট, একীভূতকরণ পরিকল্পনা এবং নীতি সুদহার পরিবর্তনের ওপর ভিত্তি করে তথ্য প্রদান করেছে। এখানে এস আলম গ্রুপসহ ব...","�্যাংক বাংলাদেশের পরিচালনা পর্ষদ ভেঙে দেওয়ার সিদ্ধান্ত নিয়েছে কেন্দ্রীয় ব্যাংক। এ সিদ্ধান্ত নিয়ে বাংলাদেশ ব্যাংকের গভর্নর ড. আহসান এইচ মনসুর বলেন, এটি সরকারের নিয়ন্ত্রণ থেকে বের করা হবে। এ সিদ্ধান্ত নিয়ে বাংলাদেশ ব্যাংকের গভর্নর বলেন, এটি স...",এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ওপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nইত্তেফাক মূলত ব্যাংকগুলোর তারল্য সংকট এবং একীভূতকরণের পরিকল্পনা নিয়ে বেশি জোর দিয়েছে। এখানে গভর্নরের বক্তব্য এবং টাস্কফোর্সের কাজকে ...
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,যুগান্তর,ঢাকা পোস্ট,"একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি মূলত বাংলাদেশ ব্যাংকের গভর্নরের বক্তব্যের ওপর ভিত্তি করে প্রস্তুত করা হয়েছে, যেখানে এস আলম গ্রুপের ব্যাংক লুটপাটের প...",ত্বে সরকার সম্মেলনে এস আলম গ্রুপের মালিকেরা বিদেশে পাচার করে দেওয়া হয়েছিল। এ সময় সরকার সম্মেলনে এস আলম গ্রুপের মালিকেরা বিদেশে পাচার করে দেওয়া হয়েছিল। এ সময় সরকার সম্মেলনে এস আলম গ্রুপের মালিকেরা বিদেশে পাচার করে দেওয়া হয়েছিল। এ সময় সরকা...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্য বিশ্লেষণ করে উত্তর দেওয়া হলো:\n\nA-এর উপস্থাপন:\nব্যাংক লুটপাট এবং এস আলম গ্রুপের সম্পদ বিক্রি করার বিষয়ে ব্যাংক গভর্নরের পদক্ষেপের ওপর বেশি জোর দেওয়া হয়েছে। এখানে গভর্নরের বক্তব্য এবং গৃহীত পদ...
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪,যমুনা টিভি,প্রদত্ত প্রতিবেদনের ভিত্তিতে তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি ঘটনার বর্ষপূর্তিকে কেন্দ্র করে এবং দিনটিকে ‘জুলাই গণঅভ্যুত্থান দিবস’ হিসেবে রাষ্ট্রীয় উদযাপনের প্রেক্ষাপটে তুলে ধরেছে।\n\n**B-এর উপস্থাপন:**\nপ্রতি...,A-এর উপস্থাপন:\nজুলাই গণঅভ্যুত্থান দিবস আজ। ছাত্র-জনতার আন্দোলনে ২০২৪ সালের ৫ আগস্ট সাবেক প্রধানমন্ত্রী শেখ হাসিনার পদত্যাগ ও দেশত্যাগের মধ্য দিয়ে আওয়ামী লীগের সাড়ে ১৫ বছরের ফ্যাসিবাদী শাসন ব্যবস্থার অবসান ঘটে।\n\nB-এর উপস্থাপন:\nশেখ হাসিনার প...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন পর্যালোচনার ভিত্তিতে আপনার প্রশ্নের উত্তর দেওয়া হলো:\n\nA-এর উপস্থাপন:\nজাগো নিউজ ২৪ জুলাই গণঅভ্যুত্থান দিবস পালনের প্রেক্ষাপটে শেখ হাসিনার পদত্যাগ ও দেশত্যাগকে একটি ঐতিহাসিক ঘটনা হিসেবে তুলে ধরেছে। এখানে আন্দোল...
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট,এখন টিভি,"আপনার অনুরোধ অনুযায়ী প্রদত্ত প্রতিবেদনের ভিত্তিতে ৬টি অংশে তুলনা নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:** প্রতিবেদনটি ৪ আগস্ট খুলনায় স্থানীয় পর্যায়ে ঘটে যাওয়া সহিংসতা, হামলা, ভাঙচুর ও আওয়ামী লীগ নেতাকর্মীদের পিছু হটার ঘটনার বিশদ বিবরণ তুলে ধরেছে।\n\...",�ায় সব স্থানে আন্তর্জাতিক সংবাদমাধ্যমের চোখ এখন রয়েছে। এ সময় আন্তর্জাতিক সংবাদমাধ্যমের চোখ এখন বাংলাদেশের দিকে রয়েছে। এ সময় আন্তর্জাতিক সংবাদমাধ্যমের চোখ এখন বাংলাদেশের দিকে রয়েছে। এ সময় আন্তর্জাতিক সংবাদমাধ্যমের চোখ এখন বাংলাদেশের দিকে রয...,"এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের উপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nঢাকা পোস্ট মূলত খুলনার ঘটনাটিকে একটি ধারাবাহিক ঘটনার বর্ণনাকারী হিসেবে তুলে ধরেছে। এখানে আন্দোলনের সূত্রপাত, ছাত্রছাত্রীদের মিছিল, দ..."
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),আজকের পত্রিকা,"নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনা নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটি একটি সরকারি সভার কার্যবিবরণী আকারে উপস্থাপিত, যেখানে উপদেষ্টা পরিষদের সিদ্ধান্ত এবং আইন উপদেষ্টার ব্রিফিংয়ের ওপর বেশি জোর দেওয়া হয়েছে।...","িবসে। সেদিন তিনি খুব উৎফুল্ল ছিলেন। আমার সাথে অনেকক্ষণ গল্প করেছেন। আমার, আমার স্ত্রী’র স্বাস্থ্যের বিষয়ে খোঁজ নিয়েছেন। তিনি নিজে অসুস্থ ছিলেন, কিন্তু সবার সুস্থতা নিয়ে তাঁর উদ্বেগ ছিল। তিনি আমাদের সাথে ছিলেন। জাতির এই গুরুত্বপূর্ণ সময়ে, যখন ...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের উপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nবাসস-এর প্রতিবেদনটি মূলত উপদেষ্টা পরিষদের বৈঠকের ওপর বেশি জোর দিয়েছে, যেখানে শোক প্রস্তাব গৃহীত হয়েছে এবং দাফন ও জানাজার বিষয়ে সিদ্ধ..."
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস),সময় সংবাদ,"একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনা নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nবাসস সরকারি সিদ্ধান্তের বিবরণ, উপদেষ্টা পরিষদের সভার কার্যবিবরণী এবং প্রধান উপদেষ্টার ব্যক্তিগত স্মৃতিচারণ ও শোকবার্তার ওপর আলোকপাত করেছে।\n\...",A-এর উপস্থাপন:\nবাসস সংবাদ সংস্থা এর প্রতিবেদন একটি সম্মত ও সম্পূর্ণ সংবাদ প্রদান করে। এর মধ্যে শোক ও স্থানীয় সম্মতি প্রকাশ করা হয়েছে। সভায় বিশেষ সভা অনুষ্ঠিত হয়েছে এবং সরকার একটি শোক প্রস্তাব গৃহীত হয়েছে। সভায় বিএনপি মহাসচিব অংশ নেন এবং সর...,এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্য বিশ্লেষণ করে আপনার প্রশ্নের উত্তর দেওয়া হলো:\n\nA-এর উপস্থাপন:\nবাসস-এর প্রতিবেদনটি মূলত উপদেষ্টা পরিষদের বিশেষ সভার মাধ্যমে খালেদা জিয়ার মৃত্যুবার্ষিকী পালন এবং সরকারের নেওয়া পদক্ষেপগুলো তুলে ...
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক,আজকের পত্রিকা,"একজন নিরপেক্ষ সংবাদ বিশ্লেষক হিসেবে প্রদত্ত প্রতিবেদন দুটির তুলনামূলক বিশ্লেষণ নিচে দেওয়া হলো:\n\n**A-এর উপস্থাপন:**\nপ্রতিবেদনটিতে নির্বাচনের সামগ্রিক তথ্য, ভোটার উপস্থিতির হার, নিরাপত্তা ব্যবস্থা এবং রাজনৈতিক প্রেক্ষাপট নিয়ে একটি পূর্ণাঙ্গ চিত্...","A-এর উপস্থাপন:\nইসি সূত্রে জানা গেছে, ত্রয়োদশ জাতীয় সংসদ নির্বাচনে ভোটার উপস্থিতির হার ৬০.৬৯ শতাংশ। পোস্টাল ব্যালটের মাধ্যমে ভোট পড়েছে ৮০ দশমিক ১১ শতাংশ, যার মধ্যে বৈধ ভোটের হার ৭০ দশমিক ২৫ শতাংশ। নারী প্রার্থীর সংখ্যা ৮৩ জন, যার মধ্যে ৬৩ জন ব...","এখানে দুটি সংবাদমাধ্যমের প্রতিবেদন থেকে প্রাপ্ত তথ্যের ওপর ভিত্তি করে একটি বিশ্লেষণ দেওয়া হলো:\n\nA-এর উপস্থাপন:\nইত্তেফাক নির্বাচনের সামগ্রিক চিত্র তুলে ধরেছে—ভোটার turnout, পোস্টাল ভোট, নিরাপত্তা ব্যবস্থা, এবং নির্বাচন কমিশনের বিভিন্ন পদক্ষেপের..."


# 12. Evaluation metrics

For **every pair**:
- Qwen vs Gemini
- Gemma vs Gemini

Metrics:
- BLEU (0–100)
- BERTScore P/R/F1
- ROUGE-1/2/L F1

In [21]:
from sacrebleu import sentence_bleu
from bert_score import score as bert_score

PUNCT = string.punctuation + "।॥“”‘’…–—«»"

def tokens(text):
    text = unicodedata.normalize("NFKC", str(text))
    text = re.sub(r"\s+", " ", text).strip()

    output = []
    for word in text.split():
        word = word.strip(PUNCT)
        if word:
            output.append(word)
    return output

def ngrams(words, n):
    return [
        tuple(words[i:i+n])
        for i in range(len(words) - n + 1)
    ]

def overlap_f1(overlap, pred_count, ref_count):
    if overlap == 0 or pred_count == 0 or ref_count == 0:
        return 0.0

    precision = overlap / pred_count
    recall = overlap / ref_count
    return 2 * precision * recall / (precision + recall)

def rouge_n(prediction, reference, n):
    pred = Counter(ngrams(tokens(prediction), n))
    ref = Counter(ngrams(tokens(reference), n))

    overlap = sum((pred & ref).values())

    return overlap_f1(
        overlap,
        sum(pred.values()),
        sum(ref.values())
    )

def lcs_length(a, b):
    previous = [0] * (len(b) + 1)

    for x in a:
        current = [0]
        for j, y in enumerate(b, start=1):
            if x == y:
                current.append(previous[j - 1] + 1)
            else:
                current.append(max(current[-1], previous[j]))
        previous = current

    return previous[-1]

def rouge_l(prediction, reference):
    pred = tokens(prediction)
    ref = tokens(reference)

    if not pred or not ref:
        return 0.0

    lcs = lcs_length(pred, ref)
    return overlap_f1(lcs, len(pred), len(ref))

def bleu(prediction, reference):
    return sentence_bleu(
        prediction,
        [reference],
        tokenize="none",
        smooth_method="exp"
    ).score

# 13. Calculate every pair's scores

In [22]:
metric_rows = []
reference = results["Gemini Reference"].tolist()

for model_name in ["Qwen Zero-Shot", "Gemma Zero-Shot"]:

    predictions = results[model_name].tolist()

    P, R, F1 = bert_score(
        predictions,
        reference,
        model_type="bert-base-multilingual-cased",
        batch_size=8,
        verbose=False
    )

    for i, row in results.iterrows():
        pred = predictions[i]
        ref = reference[i]

        metric_rows.append({
            "pair_id": row["pair_id"],
            "Incident": row["Incident"],
            "Sources": f"{row['source_a']} vs {row['source_b']}",
            "Model": model_name,
            "BLEU": bleu(pred, ref),
            "BERTScore_P": float(P[i]),
            "BERTScore_R": float(R[i]),
            "BERTScore_F1": float(F1[i]),
            "ROUGE_1_F1": rouge_n(pred, ref, 1),
            "ROUGE_2_F1": rouge_n(pred, ref, 2),
            "ROUGE_L_F1": rouge_l(pred, ref)
        })

scores = pd.DataFrame(metric_rows)

display(scores.round(4))

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,pair_id,Incident,Sources,Model,BLEU,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_1_F1,ROUGE_2_F1,ROUGE_L_F1
0,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ vs আরটিভি অনলাইন,Qwen Zero-Shot,0.2666,0.6061,0.5423,0.5724,0.0292,0.0000,0.0292
1,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট vs জাগো নিউজ ২৪,Qwen Zero-Shot,0.3780,0.5667,0.5497,0.5580,0.0537,0.0068,0.0403
2,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর vs বাংলা ট্রিবিউন,Qwen Zero-Shot,0.3109,0.5885,0.5203,0.5523,0.0244,0.0000,0.0244
3,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর vs সময় সংবাদ,Qwen Zero-Shot,0.4358,0.6210,0.5607,0.5893,0.0389,0.0078,0.0389
4,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ vs প্রথম আলো,Qwen Zero-Shot,0.3404,0.5482,0.5617,0.5548,0.0909,0.0070,0.0629
5,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ vs বাংলা ট্রিবিউন,Qwen Zero-Shot,0.5743,0.6034,0.5911,0.5972,0.0876,0.0074,0.0657
6,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো vs ঢাকা পোস্ট,Qwen Zero-Shot,0.2686,0.5718,0.5376,0.5541,0.0222,0.0000,0.0222
7,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো vs দেশ রূপান্তর,Qwen Zero-Shot,0.2950,0.5774,0.5415,0.5589,0.0160,0.0000,0.0160
8,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন vs জাগো নিউজ ২৪,Qwen Zero-Shot,0.5969,0.6158,0.5509,0.5815,0.1061,0.0082,0.0898
9,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন vs কালের কণ্ঠ,Qwen Zero-Shot,0.2908,0.5946,0.5378,0.5648,0.0961,0.0000,0.0786
10,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Qwen Zero-Shot,1.4921,0.6215,0.5668,0.5929,0.0956,0.0206,0.0751
11,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর vs প্রথম আলো,Qwen Zero-Shot,1.0832,0.6528,0.5715,0.6094,0.1027,0.0414,0.0959
12,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Qwen Zero-Shot,0.3778,0.6504,0.5704,0.6078,0.1116,0.0000,0.0797
13,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা vs আরটিভি অনলাইন,Qwen Zero-Shot,0.5639,0.5616,0.5434,0.5523,0.0602,0.0076,0.0376
14,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪ vs এনটিভি অনলাইন,Qwen Zero-Shot,0.3447,0.5963,0.5562,0.5755,0.1405,0.0167,0.0909
15,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪ vs যুগান্তর,Qwen Zero-Shot,0.5058,0.7357,0.6475,0.6888,0.1917,0.0588,0.1417
16,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,দৈনিক ইত্তেফাক vs সমকাল,Qwen Zero-Shot,1.9665,0.6260,0.5765,0.6002,0.0883,0.0508,0.0631
17,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,যুগান্তর vs ঢাকা পোস্ট,Qwen Zero-Shot,0.9534,0.5930,0.5218,0.5551,0.0858,0.0266,0.0858
18,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪ vs যমুনা টিভি,Qwen Zero-Shot,2.7892,0.7746,0.7007,0.7358,0.3256,0.1250,0.2326
19,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট vs এখন টিভি,Qwen Zero-Shot,0.7542,0.6386,0.5680,0.6012,0.1033,0.0223,0.0590
20,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs আজকের পত্রিকা,Qwen Zero-Shot,0.5526,0.6490,0.6294,0.6391,0.1498,0.0377,0.0674
21,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs সময় সংবাদ,Qwen Zero-Shot,0.7892,0.6825,0.6176,0.6484,0.2738,0.0766,0.1749
22,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক vs আজকের পত্রিকা,Qwen Zero-Shot,0.6756,0.6575,0.6470,0.6522,0.1839,0.0849,0.1303
23,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs আজকের পত্রিকা,Qwen Zero-Shot,0.9033,0.7437,0.7121,0.7275,0.2186,0.0735,0.1700
24,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক vs ঢাকা পোস্ট,Qwen Zero-Shot,0.2299,0.5778,0.5401,0.5583,0.0244,0.0000,0.0244
25,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Qwen Zero-Shot,0.4024,0.6284,0.5687,0.5970,0.0763,0.0000,0.0508
26,1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),সময় সংবাদ vs আরটিভি অনলাইন,Gemma Zero-Shot,3.9980,0.8160,0.8031,0.8095,0.4211,0.1235,0.2690
27,2,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),ঢাকা পোস্ট vs জাগো নিউজ ২৪,Gemma Zero-Shot,3.4187,0.8029,0.7849,0.7938,0.3864,0.1279,0.2081
28,3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর vs বাংলা ট্রিবিউন,Gemma Zero-Shot,4.3554,0.8088,0.7947,0.8017,0.4213,0.1977,0.2921
29,4,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",যুগান্তর vs সময় সংবাদ,Gemma Zero-Shot,1.6050,0.8060,0.7849,0.7953,0.3088,0.0936,0.2157
30,5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ vs প্রথম আলো,Gemma Zero-Shot,1.9911,0.7782,0.7792,0.7787,0.3578,0.1182,0.2255
31,6,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,সময় সংবাদ vs বাংলা ট্রিবিউন,Gemma Zero-Shot,3.5918,0.8049,0.7826,0.7936,0.3760,0.1479,0.2289
32,7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো vs ঢাকা পোস্ট,Gemma Zero-Shot,1.2966,0.7786,0.7650,0.7718,0.2915,0.0821,0.1983
33,8,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),প্রথম আলো vs দেশ রূপান্তর,Gemma Zero-Shot,1.6257,0.7769,0.7655,0.7711,0.3086,0.0862,0.1943
34,9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন vs জাগো নিউজ ২৪,Gemma Zero-Shot,5.8437,0.7947,0.7975,0.7961,0.3805,0.1550,0.2262
35,10,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),এনটিভি অনলাইন vs কালের কণ্ঠ,Gemma Zero-Shot,2.1860,0.7723,0.7679,0.7701,0.3367,0.0923,0.2092
36,11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Gemma Zero-Shot,2.9822,0.8058,0.7916,0.7986,0.3816,0.1454,0.2193
37,12,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),যুগান্তর vs প্রথম আলো,Gemma Zero-Shot,5.2668,0.8180,0.7863,0.8019,0.4401,0.1769,0.2885
38,13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),সমকাল vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Gemma Zero-Shot,4.2130,0.7886,0.7845,0.7866,0.3496,0.1344,0.2468
39,14,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),আজকের পত্রিকা vs আরটিভি অনলাইন,Gemma Zero-Shot,5.7060,0.7984,0.7722,0.7851,0.3680,0.1233,0.2187
40,15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪ vs এনটিভি অনলাইন,Gemma Zero-Shot,7.9908,0.8262,0.8047,0.8153,0.4602,0.2255,0.3363
41,16,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),জাগো নিউজ ২৪ vs যুগান্তর,Gemma Zero-Shot,3.3395,0.8127,0.7988,0.8057,0.4126,0.1902,0.2350
42,17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,দৈনিক ইত্তেফাক vs সমকাল,Gemma Zero-Shot,7.2949,0.8042,0.7928,0.7985,0.4342,0.1762,0.2632
43,18,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,যুগান্তর vs ঢাকা পোস্ট,Gemma Zero-Shot,2.1552,0.7959,0.7843,0.7901,0.2995,0.0922,0.1643
44,19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),জাগো নিউজ ২৪ vs যমুনা টিভি,Gemma Zero-Shot,3.0663,0.7915,0.7844,0.7879,0.3646,0.1204,0.2240
45,20,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),ঢাকা পোস্ট vs এখন টিভি,Gemma Zero-Shot,2.1073,0.7867,0.7755,0.7811,0.3158,0.1058,0.2105
46,21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs আজকের পত্রিকা,Gemma Zero-Shot,6.0213,0.8236,0.8010,0.8121,0.4107,0.1769,0.2187
47,22,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs সময় সংবাদ,Gemma Zero-Shot,4.0149,0.8021,0.7915,0.7968,0.3874,0.1737,0.3037
48,23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,ইত্তেফাক vs আজকের পত্রিকা,Gemma Zero-Shot,4.4538,0.8244,0.8136,0.8190,0.4214,0.1731,0.2789
49,24,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,বাংলাদেশ সংবাদ সংস্থা (বাসস) vs আজকের পত্রিকা,Gemma Zero-Shot,2.5411,0.8076,0.7936,0.8005,0.3855,0.1236,0.2682
50,25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক vs ঢাকা পোস্ট,Gemma Zero-Shot,1.3867,0.7831,0.7778,0.7804,0.3779,0.0994,0.1977
51,26,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),ইত্তেফাক vs বাংলাদেশ সংবাদ সংস্থা (বাসস),Gemma Zero-Shot,6.1990,0.8314,0.8052,0.8181,0.4333,0.2013,0.2867


# 14. FINAL RESULT — Average of all pair-wise scores

This is the main table to show your faculty.

Each value is the **average of that metric across every evaluated pair**.

In [23]:
metrics = [
    "BLEU",
    "BERTScore_P",
    "BERTScore_R",
    "BERTScore_F1",
    "ROUGE_1_F1",
    "ROUGE_2_F1",
    "ROUGE_L_F1"
]

average_scores = (
    scores.groupby("Model")[metrics]
          .mean()
          .reset_index()
)

average_scores.insert(1, "Number_of_Pairs", len(results))

display(average_scores.round(4))

,Model,Number_of_Pairs,BLEU,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_1_F1,ROUGE_2_F1,ROUGE_L_F1
0,Gemma Zero-Shot,26,3.7943,0.8015,0.7878,0.7946,0.3781,0.1409,0.2395
1,Qwen Zero-Shot,26,0.6977,0.6263,0.5781,0.6010,0.1076,0.0261,0.0787


# 15. Average score by incident
Optional, but useful to see which incidents were easier or harder.

In [24]:
incident_average = (
    scores.groupby(["Incident", "Model"])[metrics]
          .mean()
          .reset_index()
)

display(incident_average.round(4))

,Incident,Model,BLEU,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_1_F1,ROUGE_2_F1,ROUGE_L_F1
0,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),Gemma Zero-Shot,3.7084,0.8095,0.7940,0.8016,0.4037,0.1257,0.2385
1,অন্তর্বর্তী সরকার প্রতিষ্ঠা (৮ আগস্ট ২০২৪),Qwen Zero-Shot,0.3223,0.5864,0.5460,0.5652,0.0414,0.0034,0.0347
2,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",Gemma Zero-Shot,2.9802,0.8074,0.7898,0.7985,0.3651,0.1457,0.2539
3,"অর্থনৈতিক সংকট, ডলারের ঘাটতি ও আইএমএফ (IMF) ঋণ (২০২২-২০২৪)",Qwen Zero-Shot,0.3733,0.6047,0.5405,0.5708,0.0317,0.0039,0.0317
4,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,Gemma Zero-Shot,2.7914,0.7916,0.7809,0.7862,0.3669,0.1331,0.2272
5,আন্তর্জাতিক অপরাধ ট্রাইব্যুনাল (ICT) এবং শেখ হাসিনার বিচার,Qwen Zero-Shot,0.4573,0.5758,0.5764,0.5760,0.0893,0.0072,0.0643
6,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),Gemma Zero-Shot,1.4612,0.7777,0.7653,0.7714,0.3001,0.0842,0.1963
7,উত্তরায় বিমান বাহিনীর প্রশিক্ষণ বিমান দুর্ঘটনা (২০২৫),Qwen Zero-Shot,0.2818,0.5746,0.5395,0.5565,0.0191,0.0000,0.0191
8,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),Gemma Zero-Shot,4.0149,0.7835,0.7827,0.7831,0.3586,0.1237,0.2177
9,জুলাই হত্যাকাণ্ড ও ছাত্র-জনতার গণঅভ্যুত্থান (২০২৪),Qwen Zero-Shot,0.4439,0.6052,0.5444,0.5732,0.1011,0.0041,0.0842
10,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),Gemma Zero-Shot,4.1245,0.8119,0.7890,0.8002,0.4108,0.1611,0.2539
11,ডিজিটাল নিরাপত্তা আইন (DSA) ও সাইবার নিরাপত্তা আইন (CSA) বিলোপ (২০২৪),Qwen Zero-Shot,1.2876,0.6371,0.5692,0.6012,0.0992,0.0310,0.0855
12,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),Gemma Zero-Shot,4.9595,0.7935,0.7784,0.7858,0.3588,0.1288,0.2327
13,দেশজুড়ে হামের প্রাদুর্ভাব (২০২৬),Qwen Zero-Shot,0.4709,0.6060,0.5569,0.5801,0.0859,0.0038,0.0586
14,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),Gemma Zero-Shot,5.6651,0.8195,0.8018,0.8105,0.4364,0.2079,0.2856
15,বৈশ্বিক জ্বালানি সংকট ও বিশ্ববিদ্যালয় বন্ধের সিদ্ধান্ত (২০২৬),Qwen Zero-Shot,0.4252,0.6660,0.6018,0.6322,0.1661,0.0377,0.1163
16,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,Gemma Zero-Shot,4.7250,0.8001,0.7886,0.7943,0.3669,0.1342,0.2137
17,ব্যাংকিং খাতে সংস্কার এবং ‘এস আলম গ্রুপ’ ও লুটেরাদের নিয়ন্ত্রণমুক্তকরণ,Qwen Zero-Shot,1.4600,0.6095,0.5491,0.5777,0.0871,0.0387,0.0745
18,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),Gemma Zero-Shot,2.5868,0.7891,0.7799,0.7845,0.3402,0.1131,0.2172
19,শেখ হাসিনা সরকারের পতন ও দেশত্যাগ (৫ আগস্ট ২০২৪),Qwen Zero-Shot,1.7717,0.7066,0.6344,0.6685,0.2145,0.0737,0.1458
20,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,Gemma Zero-Shot,5.0181,0.8128,0.7962,0.8044,0.3991,0.1753,0.2612
21,সাবেক প্রধানমন্ত্রী বেগম খালেদা জিয়ার প্রয়াণ,Qwen Zero-Shot,0.6709,0.6658,0.6235,0.6438,0.2118,0.0572,0.1212
22,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,Gemma Zero-Shot,3.4974,0.8160,0.8036,0.8097,0.4034,0.1484,0.2735
23,২০২৬ সালের ত্রয়োদশ জাতীয় সংসদ নির্বাচন,Qwen Zero-Shot,0.7895,0.7006,0.6795,0.6899,0.2013,0.0792,0.1502
24,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),Gemma Zero-Shot,3.7928,0.8072,0.7915,0.7993,0.4056,0.1504,0.2422
25,‘জুলাই সনদ’ ও সাংবিধানিক গণভোট (২০২৬),Qwen Zero-Shot,0.3161,0.6031,0.5544,0.5777,0.0503,0.0000,0.0376

# 16. Which model scored higher?

In [25]:
comparison = []

for metric in metrics:
    best_index = average_scores[metric].idxmax()

    comparison.append({
        "Metric": metric,
        "Higher Average Model": average_scores.loc[best_index, "Model"],
        "Higher Average Score": average_scores.loc[best_index, metric]
    })

display(pd.DataFrame(comparison).round(4))

         Metric Higher Average Model  Higher Average Score
0          BLEU      Gemma Zero-Shot                3.7943
1   BERTScore_P      Gemma Zero-Shot                0.8015
2   BERTScore_R      Gemma Zero-Shot                0.7878
3  BERTScore_F1      Gemma Zero-Shot                0.7946
4    ROUGE_1_F1      Gemma Zero-Shot                0.3781
5    ROUGE_2_F1      Gemma Zero-Shot                0.1409
6    ROUGE_L_F1      Gemma Zero-Shot                0.2395


# 17. Faculty explanation

### Zero-shot
Qwen and Gemma are used **without any training or fine-tuning** on this project dataset.

### Gemini reference
Gemini's comparison is treated as the reference/ground truth according to the faculty instruction.

### Pair-wise scoring
Each Qwen and Gemma answer is compared with Gemini for the **same newspaper pair**.

### Average of all scores
If there are `N` pairs and a metric produces:

`score1, score2, ..., scoreN`

then:

**Average = (score1 + score2 + ... + scoreN) / N**

The averaging is done separately for BLEU, BERTScore and each ROUGE metric.

### Most important output
**Section 14 — FINAL RESULT — Average of all pair-wise scores**